site_name: SCOPD SIEM
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

nav:
  - Integrations: index.md
  - Features: features.md
  - XDR: xdr.md

plugins:
  - search
  - macros