site_name: SCOPD SIEM
theme:
  name: material

nav:
  - Features: index.md
  - Integrations: integration.md
  - XDR: xdr.md
  - Test: test.md

plugins:
  - search
  - macros

extra:
  syslog_port: 514